# Permalinks
permalink:           /:year/:month/:day/:title/

# Setup
title:             trinnovative blog
description:
url:               http://blog.trinnovative.de
paginate:          10
baseurl:           ""
logo:              public/logo_flat.png
social:
  type: organization
  name: trinnovative GmbH
  links:


pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  Web: 'http://www.trinnovative.de'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              trinnovative GmbH
  url:               http://www.trinnovative.de
  email:             info@trinnovative.de

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/trinnovative/trinnovative.github.io

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
